{
      "stdout": "",
      "stderr": "Error from server (InternalError): error when creating \"difftest-xtradb-whitebox-3/trial-03/mutated-0.yaml\": Internal error occurred: failed calling webhook \"validationwebhook.pxc.percona.com\": Post \"https://percona-xtradb-cluster-operator.acto-namespace.svc:443/validate-percona-xtradbcluster?timeout=10s\": dial tcp 10.96.106.61:443: connect: connection refused\n"
}