{"level":"info","ts":1679822510.7480702,"logger":"setup","msg":"Runs on","platform":"kubernetes","version":"v1.22.9"}
{"level":"info","ts":1679822510.7481933,"logger":"setup","msg":"Git commit: 46b71b736a7dcfde5e401f355a39eb8b8c65e449 Git branch: release-1-11-0 Build time: 2022-06-01T18:24:03Z"}
{"level":"info","ts":1679822510.7482116,"logger":"setup","msg":"Go Version: go1.18.2"}
{"level":"info","ts":1679822510.7482173,"logger":"setup","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1679822511.4027529,"logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":1679822511.4035034,"logger":"setup","msg":"Registering Components."}
{"level":"info","ts":1679822515.2602181,"logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/validate-percona-xtradbcluster"}
{"level":"info","ts":1679822515.2602763,"logger":"setup","msg":"Starting the Cmd."}
{"level":"info","ts":1679822515.3427422,"logger":"controller-runtime.webhook.webhooks","msg":"Starting webhook server"}
{"level":"info","ts":1679822515.34295,"msg":"Starting server","kind":"health probe","addr":"[::]:8081"}
{"level":"info","ts":1679822515.3429754,"msg":"Starting server","path":"/metrics","kind":"metrics","addr":"[::]:8080"}
{"level":"info","ts":1679822515.3431737,"msg":"attempting to acquire leader lease acto-namespace/08db1feb.percona.com...\n"}
{"level":"info","ts":1679822515.3432791,"logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}
{"level":"info","ts":1679822515.3434906,"logger":"controller-runtime.webhook","msg":"Serving webhook server","host":"","port":9443}
{"level":"info","ts":1679822515.3435788,"logger":"controller-runtime.certwatcher","msg":"Starting certificate watcher"}
{"level":"info","ts":1679822515.3681176,"msg":"successfully acquired lease acto-namespace/08db1feb.percona.com\n"}
{"level":"info","ts":1679822515.368578,"logger":"controller.perconaxtradbcluster-controller","msg":"Starting EventSource","source":"kind source: *v1.PerconaXtraDBCluster"}
{"level":"info","ts":1679822515.3686993,"logger":"controller.perconaxtradbcluster-controller","msg":"Starting Controller"}
{"level":"info","ts":1679822515.3686574,"logger":"controller.perconaxtradbclusterrestore-controller","msg":"Starting EventSource","source":"kind source: *v1.PerconaXtraDBClusterRestore"}
{"level":"info","ts":1679822515.3687468,"logger":"controller.perconaxtradbclusterrestore-controller","msg":"Starting Controller"}
{"level":"info","ts":1679822515.368809,"logger":"controller.perconaxtradbclusterbackup-controller","msg":"Starting EventSource","source":"kind source: *v1.PerconaXtraDBClusterBackup"}
{"level":"info","ts":1679822515.3689585,"logger":"controller.perconaxtradbclusterbackup-controller","msg":"Starting Controller"}
{"level":"info","ts":1679822515.644031,"logger":"controller.perconaxtradbcluster-controller","msg":"Starting workers","worker count":1}
{"level":"info","ts":1679822515.6699197,"logger":"controller.perconaxtradbclusterbackup-controller","msg":"Starting workers","worker count":1}
{"level":"info","ts":1679822515.7003403,"logger":"controller.perconaxtradbclusterrestore-controller","msg":"Starting workers","worker count":1}
{"level":"info","ts":1679822527.246052,"logger":"KubeAPIWarningLogger","msg":"policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget"}
{"level":"info","ts":1679822528.5080948,"caller":"pxc/backup.go:87","msg":"Creating or updating backup job","name":"ac58c-sat-night-backup","schedule":"0 0 * * 6"}
{"level":"info","ts":1679822528.5081751,"caller":"pxc/backup.go:87","msg":"Creating or updating backup job","name":"ac58c-daily-backup","schedule":"0 0 * * *"}
{"level":"info","ts":1679822528.5084763,"logger":"perconaxtradbcluster","caller":"pxc/version.go:65","msg":"add new job","cluster":"test-cluster","namespace":"acto-namespace","schedule":"0 4 * * *"}
{"level":"info","ts":1679822528.5085173,"logger":"perconaxtradbcluster","caller":"pxc/version.go:107","msg":"add new job","cluster":"test-cluster","namespace":"acto-namespace","name":"ensure-version/acto-namespace/test-cluster","schedule":"0 4 * * *"}
{"level":"error","ts":1679823381.668133,"logger":"controller.perconaxtradbcluster-controller","msg":"Reconciler error","name":"test-cluster","namespace":"acto-namespace","error":"Operation cannot be fulfilled on perconaxtradbclusters.pxc.percona.com \"test-cluster\": StorageError: invalid object, Code: 4, Key: /registry/pxc.percona.com/perconaxtradbclusters/acto-namespace/test-cluster, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 587cde82-f847-48d2-bbf7-666dee3ef84f, UID in object meta: 36db2c5e-e810-4093-ba39-b2bbf2e62118","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227"}
{"level":"info","ts":1679823434.9567657,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823443.3447857,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823451.5367513,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823459.724815,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823468.108691,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823476.3327198,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823484.7487104,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823492.9407234,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823501.1647527,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823509.549074,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823517.836742,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823526.22077,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823534.480692,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823542.668672,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823551.052752,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823559.2447212,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823567.5007694,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823575.724747,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823583.9528103,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823592.3327641,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823600.5607448,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823608.8127604,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823617.0367723,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823625.2327895,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823633.520779,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823641.7417207,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823649.964702,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823658.3167481,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823666.5727794,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823675.0247824,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823683.2447593,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823691.472738,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823699.7287726,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823708.140704,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823716.3648028,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823724.7167447,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823732.9447558,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823741.4207342,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823749.6447577,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823758.0287406,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823766.2527986,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823774.4447296,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823782.8327296,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823791.052784,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823799.30875,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823807.5328138,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823815.7567768,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823824.208708,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823832.4607296,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823840.7166739,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823848.9406836,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823857.164579,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823865.5166314,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823873.7407188,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823881.9687102,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823890.3486814,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823898.5407147,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823906.9246955,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823915.1167529,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823923.5327377,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823931.7566996,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823939.948679,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823948.1407335,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823956.3326883,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823964.7167637,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823972.9407613,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823981.164783,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679823989.5487127,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.244.21:3306: connect: connection refused"}
{"level":"info","ts":1679824032.4804158,"logger":"perconaxtradbcluster","caller":"pxc/upgrade.go:267","msg":"statefulSet was changed, run smart update","cluster":"test-cluster","namespace":"acto-namespace"}
{"level":"error","ts":1679824039.562827,"logger":"controller.perconaxtradbcluster-controller","msg":"Reconciler error","name":"test-cluster","namespace":"acto-namespace","error":"pxc upgrade error: get primary pod: failed to get proxySQL db: dial tcp 10.96.230.165:3306: connect: connection refused","errorVerbose":"dial tcp 10.96.230.165:3306: connect: connection refused\nfailed to get proxySQL db\ngithub.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc.(*ReconcilePerconaXtraDBCluster).getPrimaryPod\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc/upgrade.go:516\ngithub.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc.(*ReconcilePerconaXtraDBCluster).smartUpdate\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc/upgrade.go:284\ngithub.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc.(*ReconcilePerconaXtraDBCluster).updatePod\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc/upgrade.go:220\ngithub.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc.(*ReconcilePerconaXtraDBCluster).Reconcile\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc/controller.go:346\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571\nget primary pod\ngithub.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc.(*ReconcilePerconaXtraDBCluster).smartUpdate\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc/upgrade.go:286\ngithub.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc.(*ReconcilePerconaXtraDBCluster).updatePod\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc/upgrade.go:220\ngithub.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc.(*ReconcilePerconaXtraDBCluster).Reconcile\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc/controller.go:346\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571\npxc upgrade error\ngithub.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc.(*ReconcilePerconaXtraDBCluster).Reconcile\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc/controller.go:348\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227"}
{"level":"info","ts":1679824079.532706,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.230.165:3306: connect: connection refused"}
{"level":"info","ts":1679824087.8246124,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.230.165:3306: connect: connection refused"}
{"level":"info","ts":1679824096.0448053,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.230.165:3306: connect: connection refused"}
{"level":"info","ts":1679824214.1568878,"logger":"perconaxtradbcluster","caller":"pxc/upgrade.go:267","msg":"statefulSet was changed, run smart update","cluster":"test-cluster","namespace":"acto-namespace"}
{"level":"error","ts":1679824221.2691271,"logger":"controller.perconaxtradbcluster-controller","msg":"Reconciler error","name":"test-cluster","namespace":"acto-namespace","error":"pxc upgrade error: get primary pod: failed to get proxySQL db: dial tcp 10.96.242.102:3306: connect: connection refused","errorVerbose":"dial tcp 10.96.242.102:3306: connect: connection refused\nfailed to get proxySQL db\ngithub.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc.(*ReconcilePerconaXtraDBCluster).getPrimaryPod\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc/upgrade.go:516\ngithub.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc.(*ReconcilePerconaXtraDBCluster).smartUpdate\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc/upgrade.go:284\ngithub.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc.(*ReconcilePerconaXtraDBCluster).updatePod\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc/upgrade.go:220\ngithub.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc.(*ReconcilePerconaXtraDBCluster).Reconcile\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc/controller.go:346\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571\nget primary pod\ngithub.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc.(*ReconcilePerconaXtraDBCluster).smartUpdate\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc/upgrade.go:286\ngithub.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc.(*ReconcilePerconaXtraDBCluster).updatePod\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc/upgrade.go:220\ngithub.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc.(*ReconcilePerconaXtraDBCluster).Reconcile\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc/controller.go:346\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571\npxc upgrade error\ngithub.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc.(*ReconcilePerconaXtraDBCluster).Reconcile\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc/controller.go:348\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227"}
{"level":"error","ts":1679824221.39138,"logger":"controller.perconaxtradbcluster-controller","msg":"Reconciler error","name":"test-cluster","namespace":"acto-namespace","error":"pxc upgrade error: update error: Operation cannot be fulfilled on statefulsets.apps \"test-cluster-pxc\": the object has been modified; please apply your changes to the latest version and try again","errorVerbose":"Operation cannot be fulfilled on statefulsets.apps \"test-cluster-pxc\": the object has been modified; please apply your changes to the latest version and try again\nupdate error\ngithub.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc.(*ReconcilePerconaXtraDBCluster).updatePod\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc/upgrade.go:213\ngithub.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc.(*ReconcilePerconaXtraDBCluster).Reconcile\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc/controller.go:346\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571\npxc upgrade error\ngithub.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc.(*ReconcilePerconaXtraDBCluster).Reconcile\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/pkg/controller/pxc/controller.go:348\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/src/github.com/percona/percona-xtradb-cluster-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227"}
{"level":"info","ts":1679824261.4208155,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.242.102:3306: connect: connection refused"}
{"level":"info","ts":1679824269.7407727,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.242.102:3306: connect: connection refused"}
{"level":"info","ts":1679824277.9326384,"logger":"perconaxtradbcluster","caller":"pxc/controller.go:465","msg":"reconcile replication error","cluster":"test-cluster","namespace":"acto-namespace","err":"get primary pxc pod: failed to get proxySQL db: dial tcp 10.96.242.102:3306: connect: connection refused"}

